# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(max_length=50)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Owner.Address')),
                ('owners', models.ManyToManyField(to='Owner.Owner')),
                ('phones', models.ManyToManyField(to='Owner.Phone')),
            ],
        ),
        migrations.AddField(
            model_name='pen',
            name='ranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.Ranch'),
        ),
        migrations.AddField(
            model_name='lot',
            name='pen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.Pen'),
        ),
        migrations.AddField(
            model_name='animallocation',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Location.Lot'),
        ),
        migrations.AddField(
            model_name='animallocation',
            name='pen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Location.Pen'),
        ),
        migrations.AddField(
            model_name='animallocation',
            name='ranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.Ranch'),
        ),
    ]
