# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('street2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_cat', models.IntegerField(choices=[(1, 'home'), (2, 'work'), (3, 'fax'), (4, 'cell'), (5, 'other')])),
                ('phone_num', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('owner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Owner.Owner')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('Owner.owner',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('owner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Owner.Owner')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
            ],
            bases=('Owner.owner',),
        ),
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Owner.Address'),
        ),
        migrations.AddField(
            model_name='owner',
            name='phones',
            field=models.ManyToManyField(to='Owner.Phone'),
        ),
        migrations.AddField(
            model_name='company',
            name='people',
            field=models.ManyToManyField(to='Owner.Person'),
        ),
    ]
