# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EPDs',
            fields=[
                ('numbercollection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Performance.NumberCollection')),
                ('CED', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Calving Ease Direct')),
                ('CED_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Calving Ease Direct Accuracy')),
                ('BW', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Birth Weight')),
                ('BW_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Birth Weight Accuracy')),
                ('WW', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Weaning Weight')),
                ('WW_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Weaning Weight Accuracy')),
                ('YW', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Yearling Weight')),
                ('YW_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Yearling Weight Accuracy')),
                ('RADG', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Residual Average Daily Gain')),
                ('RADG_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Residual Average Daily Gain Accuracy')),
                ('DMI', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Dry Matter Intake')),
                ('DMI_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Dry Matter Intake Accuracy')),
                ('YH', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Yearling Height')),
                ('YH_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Yearling Height Accuracy')),
                ('SC', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Scrotal Circumference')),
                ('SC_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Scrotal Circumference Accuracy')),
                ('Doc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Docility')),
                ('Doc_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Docility Accuracy')),
                ('HP', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Heifer Pregnancy')),
                ('HP_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Heifer Pregnancy Accuracy')),
                ('CEM', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Calving Ease Maternal')),
                ('CEM_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Calving Ease Maternal Accuracy')),
                ('Milk', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Maternal Milk')),
                ('Milk_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Maternal Milk Accuracy')),
                ('MkH', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Maternal Herds')),
                ('MkH_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Maternal Herds Accuracy')),
                ('MkD', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Maternal Daughters')),
                ('MkD_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Maternal Daughters Accuracy')),
                ('MW', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Mature Weight')),
                ('MW_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Mature Weight Accuracy')),
                ('MH', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Mature Height')),
                ('MH_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Mature Height Accuracy')),
                ('valEN', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Cow Energy Value')),
                ('CW', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Carcass Weight')),
                ('CW_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Carcass Weight Acccuracy')),
                ('Marb', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Marbling')),
                ('Marb_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Marbling Accuracy')),
                ('RE', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Ribeye Area')),
                ('RE_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Ribeye Area Accuracy')),
                ('Fat', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Fat Thickness')),
                ('Fat_acc', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Fat Thickness Accuracy')),
                ('CGrp', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Contemporary Groups')),
                ('CPg', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Contemporary Progeny')),
                ('UGrp', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Ultrasound Groups')),
                ('UPg', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Ultrasound Progeny')),
                ('valW', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Weaned Calf Value')),
                ('valF', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Feedlot Value')),
                ('valG', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Grid Value')),
                ('valQG', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Quality Grade')),
                ('valYG', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Yield Grade')),
                ('valB', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Beef Value')),
            ],
            bases=('Performance.numbercollection',),
        ),
        migrations.CreateModel(
            name='MeasuredDated',
            fields=[
                ('numbercollection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Performance.NumberCollection')),
                ('BW_mes', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Measured Birth Weight')),
                ('WW_mes', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Measured Weaning Weight')),
                ('WH_mes', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Measured Weaning Height')),
                ('YW_mes', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Measured Yearling Weight')),
                ('YH_mes', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Measured Yearling Height')),
                ('SC_mes', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Measured Scrotal Circumference')),
            ],
            bases=('Performance.numbercollection',),
        ),
        migrations.AddField(
            model_name='performance',
            name='epds',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epds_set', to='Performance.NumberCollection'),
        ),
        migrations.AddField(
            model_name='performance',
            name='measured_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measured_data_set', to='Performance.NumberCollection'),
        ),
    ]
